### ISSUE TITLE
Why 192.168.33.10?

### ISSUE THREAD

**Issue by LimeBlast** [fideloper/Vaprobash#161]
Not an issue, but a question - possibly a silly one - but one I'm interested in regardless.

Why did you choose `192.168.33.10` as the default IP address of the box? What was it about that particular combination of numbers which made it appealing?

I only ask because I use the tool at https://puphpet.com/ for one of my other projects, and they have a default IP address of `192.168.56.101`. I've also seen a couple other Vagrant projects which use this IP address as well, which lead me to believe it was some type of Vagrant standard.

Cheers

**Comment by luigimannoni** [comment]
This page is the first result on google for that IP address. I was asking myself the same question since I copied a Vagrantfile from a co-worker 6 months ago and I am still using the same IP address across all my projects

**Comment by fideloper** [comment]
Nice! :beers:
