### ISSUE TITLE
Shell provisioning path doesn't exist

### ISSUE THREAD

**Issue by whoisandy** [fideloper/Vaprobash#30]
Says path doesn't exist on the host system. Using Vagrant 1.2.2 btw, are there any compatibility issues ? Errors appear as shown below.

There are errors in the configuration of this machine. Please fix
the following errors and try again:

shell provisioner:
- `path` for shell provisioner does not exist on the host system: /Users/Asher/Git/goblog/https:/raw.github.com/fideloper/Vaprobash/master/scripts/nginx.sh

**Comment by illogicalextend** [comment]
FYI if you're using windows, be careful about hidden file extensions. What looks like "bootstrap.sh" may actually be "bootstrap.sh.txt".
