### ISSUE TITLE
Access denied for user 'root'@'localhost'

### ISSUE THREAD

**Issue by lewiswharf** [fideloper/Vaprobash#300]
Starting an SSH session in PHPStorm and running Laravel's `php artisan migrate` results in following error:

```
[PDOException]                                                                          
SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)  
```

Password set to `root` in Vagrantfile and app config.php. I can `mysql -u root -p` and login with password `root` no problem.

Any ideas?

**Comment by 07958** [comment]
i d'ont understand that error :(
