### ISSUE TITLE
make xdebug optional

### ISSUE THREAD

**Issue by JulienTant** [fideloper/Vaprobash#400]
Hi there,

When xdebug is enabled, your php project becomes slow and running unit test becomes a nightmare on big project.

It would be aweoms to enable or disable it during provision with a simple variable :

```
enable_xdebug = true/false
```

prepending a ';' before the line would be enough.

What do you think ?

**Comment by Intrepidity** [comment]
The only thing that comes to mind is that some composer packages like CodeSniffer depend on xdebug (and phpunit if you want to generate code coverage reports). Other than that I don't think there's any dependency. I can send a PR over the weekend to fix this.
