### ISSUE TITLE
Has anyone used vaprobash for Magento installations?

### ISSUE THREAD

**Issue by jahvi** [fideloper/Vaprobash#425]
I'm having issues trying to log in to the admin area using apache and nginx, it's most likely related to [this](http://magento.stackexchange.com/a/26083) but I haven't been able to pinpoint the problem. I've used other boxes like [this one](https://github.com/r-baker/simple-magento-vagrant) without problems so I think it must be a setting or config messing it up.

**Comment by jahvi** [comment]
Here's the diff: https://www.diffchecker.com/flwr60rl

Left is the default, Right is ondrej's. There are some differences with session settings I guess that's the cause.

**Comment by fideloper** [comment]
Wonder of the session save path is the issue. Seems like the most likely
based on that.

**Comment by gayanhewa** [comment]
I have used it but with a few modifications to the scripts. From the version of PHP that it installs to a few other changes. Never tried the combination with nginx but mostly with Apache.
