### ISSUE TITLE
Mailcatcher not sending emails

### ISSUE THREAD

**Issue by jahvi** [fideloper/Vaprobash#430]
I just tried sending an email with PHP but it times out if mailcatcher is installed, I think there's an extra `'` character in the IP here: https://github.com/fideloper/Vaprobash/blob/master/scripts/mailcatcher.sh#L39

However I fixed it and it doesn't look like that's the problem, it seems that the issue is related to the `--foreground` flag, if I keep it then the mailcatcher script hangs when it reaches [this point](https://github.com/fideloper/Vaprobash/blob/master/scripts/mailcatcher.sh#L39) but if I remove it then outgoing emails don't work. I removed the flag during provisioning and ran `mailcatcher --foreground --http-ip=0.0.0.0` after it was finished and everything worked as expected.

PS: Most likely related to [this issue](https://github.com/sj26/mailcatcher/issues/182) in the mailcatcher repo

**Comment by badams** [comment]
Related to #428, looks like an issue with the upstart script.

**Comment by fideloper** [comment]
I'ved pulled that PR in, if you want to rebuild a server based on the
"master" branch. I'll push that as a new release soon.
