### ISSUE TITLE
Permission denied on apache2 logs

### ISSUE THREAD

**Issue by damianlewis** [fideloper/Vaprobash#436]
I can't access the apache2 log directory? I can view the log file is by using:

`$ sudo cat /var/log/apache2/192.168.22.10.xip.io-error.log`

but I can't access the `/var/log/apache2` directory. I just get

`-bash: cd: /var/log/apache2: Permission denied`

**Comment by fideloper** [comment]
Try using "sudo su" to login as root, then "cd" into them. This is normal
behavior, as using "sudo" with cat will work fine, but some operations like
CD are "weird" in their behavior.

so:

sudo su
cd /var/log/apache2
