### ISSUE TITLE
proxy_fcgi:error failed to make connection to backend

### ISSUE THREAD

**Issue by cmosguy** [fideloper/Vaprobash#437]
@fideloper 

Can you remind me again how to fix the error issue when you have:

```bash
[Fri Jan 30 15:35:59.863091 2015] [proxy:error] [pid 3615:tid 140281718486784] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (*) failed
[Fri Jan 30 15:35:59.863168 2015] [proxy_fcgi:error] [pid 3615:tid 140281718486784] [client 198.182.56.5:47727] AH01079: failed to make connection to backend: 127.0.0.1
```

Here is my /etc/apache2/sites-enabled/laravel4.162.243.55.229.xip.io.conf:
```apache
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName laravel4.162.243.55.229.xip.io


    DocumentRoot /vagrant/server/laravel4/public


    <Directory /vagrant/server/laravel4/public>
        Options -Indexes +FollowSymLinks +MultiViews
        AllowOverride All
        Require all granted

        <FilesMatch \.php$>
            # Change this "proxy:unix:/path/to/fpm.socket"
            # if using a Unix socket
            SetHandler "proxy:fcgi://127.0.0.1:9000"
        </FilesMatch>
    </Directory>


    ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9000/vagrant/server/laravel4/public/$1

    ErrorLog ${APACHE_LOG_DIR}/laravel4.162.243.55.229.xip.io-error.log

    # Possible values include: debug, info, notice, warn, error, crit,
    # alert, emerg.
    LogLevel warn

    CustomLog ${APACHE_LOG_DIR}/laravel4.162.243.55.229.xip.io-access.log combined

    #turning on the authentication header
    RewriteEngine on
    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]


</VirtualHost>
<VirtualHost *:443>
    ServerAdmin webmaster@localhost
    ServerName laravel4.162.243.55.229.xip.io


    DocumentRoot /vagrant/server/laravel4/public

    ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9000/vagrant/server/laravel4/public/$1

    <Directory /vagrant/server/laravel4/public>
        Options -Indexes +FollowSymLinks +MultiViews
        AllowOverride All
        Require all granted

        <FilesMatch \.php$>
            # Change this "proxy:unix:/path/to/fpm.socket"
            # if using a Unix socket
            SetHandler "proxy:fcgi://127.0.0.1:9000"
        </FilesMatch>
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/laravel4.162.243.55.229.xip.io-error.log

    # Possible values include: debug, info, notice, warn, error, crit,
    # alert, emerg.
    LogLevel warn

    CustomLog ${APACHE_LOG_DIR}/laravel4.162.243.55.229.xip.io-access.log combined

    SSLEngine on

    SSLCertificateFile  /etc/ssl/xip.io/xip.io.crt
    SSLCertificateKeyFile /etc/ssl/xip.io/xip.io.key

    <FilesMatch "\.(cgi|shtml|phtml|php)$">
        SSLOptions +StdEnvVars
    </FilesMatch>

    BrowserMatch "MSIE [2-6]" \
        nokeepalive ssl-unclean-shutdown \
        downgrade-1.0 force-response-1.0
    # MSIE 7 and newer should be able to use keepalive
    BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
</VirtualHost>

```

**Comment by fideloper** [comment]
Howdy!
There could be a few reasons for this - What you have there looks like log entries from `/var/log/apache2/laravel4.162.243.55.229.xip.io-error.log`, correct?

(You're already a step ahead going to the logs :D )

This sounds like PHP5-FPM might not be listening on 127.0.0.1 or is not accepting connections from localhost.

I would check:

* Run `sudo service apache2 configtest` and see if there are any errors
* Ensure php5-fpm is configured OK and running:
    * `sudo service php5-fpm configtest`
    * `sudo service php5-fpm status`

Ensure that `/etc/php5/fpm/pool.d/www.conf` has the `listen` set to `127.0.0.1:9000`, which Apache is attempting to send PHP requests to (it could still be set to the default `/var/run/php5-fpm.sock` file).

Ensure that `/etc/php5/fpm/pool.d/www.conf` isn't restricting localhost connections (127.0.0.1) via the `;listen.allowed_clients = 127.0.0.1` directive - keep that commented out, or set it to 127.0.0.1.

Be sure to restart/reload apache/php5-fpm after any changes to their config files!

Let me know what you see, hope this helps.

**Comment by cmosguy** [comment]
@fideloper thanks for your quick response:

ran the following
```shell
apachectl configtest
Syntax OK
service php5-fpm configtest
#returns nothing
service php5-fpm status
php5-fpm stop/waiting
```

I checked that the www.conf has the following:
```bash
listen = 127.0.0.1:9000
listen.allowed_clients = 127.0.0.1
```

I made sure to do the restart/reload for both apache/php5-fpm (still didn't change anything), but still hitting the issue somehow.  

Any other ideas here?

Thanks for your time!
Adam

**Comment by fideloper** [comment]
Php5-fpm being "stop/waiting" means it's not running, so there's something going on with it. Assuming you've tried to restart/start it (`sudo service php5-fpm start`) and it still doesn't run, check out `/var/log/php5-fpm.log` and see if you see any error messages in there. You may find a config issue from there, or hopefully something that explains why it won't start.

**Comment by cmosguy** [comment]
@fideloper 

That was my same conclusion, i am looking at the /var/log/php5-fpm.log:
```baseh
[30-Jan-2015 19:13:48] NOTICE: configuration file /etc/php5/fpm/php-fpm.conf test is successful

[30-Jan-2015 19:13:48] NOTICE: configuration file /etc/php5/fpm/php-fpm.conf test is successful

[30-Jan-2015 19:13:49] NOTICE: configuration file /etc/php5/fpm/php-fpm.conf test is successful

[30-Jan-2015 19:13:49] NOTICE: configuration file /etc/php5/fpm/php-fpm.conf test is successful
:


[30-Jan-2015 19:13:48] NOTICE: configuration file /etc/php5/fpm/php-fpm.conf test is successful

[30-Jan-2015 19:13:48] NOTICE: configuration file /etc/php5/fpm/php-fpm.conf test is successful

[30-Jan-2015 19:13:49] NOTICE: configuration file /etc/php5/fpm/php-fpm.conf test is successful

[30-Jan-2015 19:13:49] NOTICE: configuration file /etc/php5/fpm/php-fpm.conf test is successful
```

Something is not adding up here, the php5-fpm.log shows no issues during the start process.  But there seems to be something causing it to die.   I am rather puzzled ATM....

**Comment by fideloper** [comment]
hrmmm yeah. Could be a bunch of things. In general, I would try:

1. `sudo tail -n 50 -f /var/log/php5-fpm.log` (see last 50 lines instead of the default, the error might be up higher)
2. Tail the php5-fpm log in one session and restart php5-fpm in another, so you can see what gets spit out to the log while you start/restart FPM
3. `ps aux | grep php` to check if existing running php5-fpm processes still exist (zombie processes). Kill them `kill -9 process-id-here` if they exist (php5-fpm ones specifically)
3. If php5-fpm is truly stopped and no processes are showing, try starting the process yourself manually and seeing if it outputs anything useful `/usr/sbin/php5-fpm --nodaemonize --fpm-config /etc/php5/fpm/php-fpm.conf`

**Comment by fideloper** [comment]
(The common theme amongst all these replies is attempting to get a useful error message :D).

Don't forget the old advice "turn it off and back on again" also if all else fails :D (A complete `vagrant halt` and `vagrant up`, not just `vagrant suspend`. `vagrant reload` will do as well).

**Comment by cmosguy** [comment]
@fideloper 

I am using vaprobash with --provider=digital_ocean here.

Here is more information, I started php5-fpm manually and i am seeing this

```
sudo /usr/sbin/php5-fpm --fpm-config /etc/php5/fpm/php-fpm.conf
[30-Jan-2015 19:29:31] ERROR: [pool www] cannot get uid for user 'vagrant'
[30-Jan-2015 19:29:31] ERROR: FPM initialization failed
```

**Comment by cmosguy** [comment]
@fideloper 

when I do an ubuntu image with digital ocean, it does not have a "vagrant" user.  Do you know where php5-fpm is trying to look for the "vagrant" user?

**Comment by fideloper** [comment]
Ah, that's very good to know, thank you!

Therein lies the issue, apparently!

Vaprobash attempts to make php-fpm run as user "vagrant", but it appears the box used with the DO provider doesn't create a user "vagrant" - if you SSH into the box directly, what's the username used?

In your `www.conf` file, perhaps change all the users from "vagrant" back to the default "www-data" and see if it starts then.

**Comment by fideloper** [comment]
(I haven't used that personally, it was a community submission)

**Comment by fideloper** [comment]
That work out?

**Comment by cmosguy** [comment]
@fideloper 

Thanks for your help! Yes it worked out, what happened was i don't have a user called "vagrant" on digital ocean.  I think I'll create the user and in the future deployments just use that.

However, it would be nice in to have this a variable so there is some flexibility for deployment.  Instead of it hardcoded to vagrant to have something else and pass it as a variable in the script and set it in the Vagrantfile.

BTW, the reason why I am steering to digitalocean rather than AWS, is because it is significantly cheaper.

Thanks again for your world class support!

Adam

**Comment by fideloper** [comment]
Cool!

Keep in mind that Vapro is better suited for dev and production boxes, since it doesn't take into account any security stuff such as firewalls, and does turn on things like error reporting and php's xdebug.

Right, I'll see what we can do abotu the DO provider - that will need some work to clean up.

Thanks for the help and time, this brings up a bug report I'll create with the username thing.

**Comment by vancouverwill** [comment]
hey guys fyi this helped me out. `sudo /usr/sbin/php5-fpm` was the key as I could see the errors with loading php5-fpm, not sure why but when I run `sudo service php5-fpm start` I didn't get any info. Anyway all good now, just thought you might like to know that it helped me out :)

**Comment by macfredd** [comment]
For those that are running your system under Selinux and get the same issue reported here, you need to enable [outbound connections](https://wiki.centos.org/TipsAndTricks/SelinuxBooleans#line-44)

/usr/sbin/setsebool -P httpd_can_network_connect 1
