### ISSUE TITLE
Can we have neo4j installation for databases as well

### ISSUE THREAD

**Issue by bumstyla** [fideloper/Vaprobash#445]
I would love it if we can have neo4j installation in the database options. I would try to   do it but you are the server hacker and know the best way to do it.

**Comment by fideloper** [comment]
Looks fairly easy [see here](https://www.digitalocean.com/community/tutorials/how-to-install-neo4j-on-an-ubuntu-vps) - Would you like to try to contribute a neo4js.sh script?

Thanks!

**Comment by fideloper** [comment]
(I would pretty much just copy the process they have there :D )

**Comment by fideloper** [comment]
Added!
