### ISSUE TITLE
unknown mount option `noatime'

### ISSUE THREAD

**Issue by erdemkeren** [fideloper/Vaprobash#446]
When I try to vagrant up, I get
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3`,nolock,vers=3,udp,noatime core /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant`,nolock,vers=3,udp,noatime core /vagrant

The error output from the last command was:

stdin: is not a tty
unknown mount option `noatime'
valid options:
  rw         mount read write (default)
  ro         mount read only
  uid       =<arg> default file owner user id
  gid       =<arg> default file owner group id
  ttl       =<arg> time to live for dentry
  iocharset =<arg> i/o charset (default utf8)
  convertcp =<arg> convert share name from given charset to utf8
  dmode     =<arg> mode of all directories
  fmode     =<arg> mode of all regular files
  umask     =<arg> umask of directories and regular files
  dmask     =<arg> umask of directories
  fmask     =<arg> umask of regular files

**Comment by fideloper** [comment]
Not sure why that's not an option, sounds odd, but simplest thing would be
to take out the noatime option and "vagrant reload". You're using the
default vagrantfile (including the box) that comes with this project?

Are you using virtualbox, or a different provider (digital ocean, vmware).?

**Comment by k2levin** [comment]
I'm also facing the same issue

when removing the [noatime] option, then another issue [nolock] option come out
In the end, remove the whole line

using the default vagrantfile from this repo, Win8.1, VirtualBox

**Comment by samjulien** [comment]
I was having the same problem running on a Windows 8.1 host. It turns out the correct mount options are `['dmode=777','fmode=777']`. Replacing the mount options with that and running `vagrant reload` caused everything to work correctly for me. 

Wondering if maybe in a future release you could have an if/else block for if the host is Windows use those mount options, otherwise (*nix machines) use the default? Maybe something like this:

```ruby
# Use NFS for the shared folder
if Vagrant::Util::Platform.windows?
config.vm.synced_folder ".", "/vagrant",
            id: "core",
            :nfs => true,
            :mount_options => ['dmode=777','fmode=777']
else
config.vm.synced_folder ".", "/vagrant",
            id: "core",
            :nfs => true,
           :mount_options => ['nolock,vers=3,udp,noatime']
end
```

**Comment by fideloper** [comment]
That''d be cool, thanks! Is that a valid IF block that vagrant provides? It looks like there's [something slightly different in this (oldish) SO question](http://stackoverflow.com/questions/18439002/vagrant-how-to-disable-nfs-sync-folders-for-windows-host), however I do see the method you're talking about [here](http://www.rubydoc.info/github/mitchellh/vagrant/Vagrant/Util/Platform#windows%3F-class_method).

(Any idea on which might be preferred?) 

Thanks, that's a great idea!

**Comment by samjulien** [comment]
I honestly am not sure -- I saw something similar in another GitHub discussion about a different issue, and I looked up that boolean in the Vagrant documentation, but I'm not sure which is preferred. I wonder if we could get an answer from Vagrant. Also, that SO you link to makes me curious if the `:nfs` should actually be false in the Windows config. I'll try to do a little more digging and experimentation on my side.

**Comment by fideloper** [comment]
hmm yeah, I can tweet at them and see if they answer, think they're pretty good about that line of communication.

NFS has traditionally not worked on Windows without an extra plugin, I believe. However, I'm not actually 100% sure that's still true! (I do zero development on Windows now a days)

**Comment by Superjo149** [comment]
Installing this https://github.com/GM-Alex/vagrant-winnfsd on windows fixed it for me.

**Comment by erdemkeren** [comment]
Closing the issue due to inactivity.
