### ISSUE TITLE
404 rabbitmq.sh in 1.3.1 branch

### ISSUE THREAD

**Issue by kwolniak** [fideloper/Vaprobash#457]
https://raw.githubusercontent.com/fideloper/Vaprobash/1.3.1/scripts/rabbitmq.sh
Error 404

**Comment by fideloper** [comment]
Rabbitmq only exists on the master branch, it's coming up a pending release of 1.3.1. or 1.4.0 (likely the latter).

Is this version referenced somewhere?

**Comment by kwolniak** [comment]
@fideloper When we make 
`curl -L http://bit.ly/vaprobash > Vagrantfile` we get Vagrantfile with `github_branch   = "1.3.1"`

and 
```
Install RabbitMQ
config.vm.provision "shell", path: "#{github_url}/scripts/rabbitmq.sh", args: [rabbitmq_user, rabbitmq_password]
```

so we get 404. When I change branch to master it works.

**Comment by fideloper** [comment]
Gotcha, I see what's going on there. In the meantime, try using "master" as
the branch instead of 1.3.1.

Thanks!
