### ISSUE TITLE
Slow when connecting to Remote Databases

### ISSUE THREAD

**Issue by gayanhewa** [fideloper/Vaprobash#459]
Hi All,

has anyone noticed a slow query execution time when using a Vagrant box to connect to a remote database.

ie. AWS RDS + Local Laravel App = 30+ Sec query time for a select. 

Its has a ok response time on local db.

**Comment by fideloper** [comment]
My first guess is that this would be related to DNS lookup, which is a common-ish issue. Check out the readme  here, point 3 about the DNS options: https://github.com/fideloper/Vaprobash#the-vagrantfile

Try adding those to your vagrantfile and reloading the server!

**Comment by gayanhewa** [comment]
:+1:  this solved it

**Comment by fideloper** [comment]
:beer:
