### ISSUE TITLE
Modify php.ini configuration

### ISSUE THREAD

**Issue by wasimkham** [fideloper/Vaprobash#464]
More of a question than an issue, but with your fantastic script - is it possible to set php.ini configuration like post_max_size and upload_max_filesize?

**Comment by fideloper** [comment]
The script doesn't have a place for that right now, you'd have to do that after provisioning.

* php.ini for php-fpm: `/etc/php5/fpm/php.ini`
* php.ini for cli: `/etc/php5/cli/php.ini`

**Comment by thibmaek** [comment]
Something like `echo "upload_max_filesize = \"200\"" >> /etc/php5/fpm/php.ini` would work in the php provisioning script wouldn't it?

**Comment by wasimkham** [comment]
@thibmaek I've just created a custom bash script in the vagrant file
```
$script = <<SCRIPT
sudo sed -i "s/upload_max_filesize = .*/upload_max_filesize = 100M/" /etc/php5/fpm/php.ini
sudo sed -i "s/post_max_size = .*/post_max_size = 100M/" /etc/php5/fpm/php.ini
sudo sed -i "s/memory_limit = .*/memory_limit = 512M/" /etc/php5/fpm/php.ini

sudo service php5-fpm restart
SCRIPT

Vagrant.configure("2") do |config|
...
config.vm.provision "shell", inline: $script

end
```
