### ISSUE TITLE
Debian 8 (jessie) base box as opposed to Ubuntu

### ISSUE THREAD

**Issue by jackyliang** [fideloper/Vaprobash#467]
Hi there!

I love everything about this. My question is - is it possible to use Debian 8.0 (jessie) as opposed to the Ubuntu build for this Vagrantfile? Reason being, my production server uses Debian 8.0, and I'd like to keep the distro the same. Or does it not matter too much?

Regards,

jacky

**Comment by fideloper** [comment]
Hello!
The main difference between the two is that some packages here use some PPA repositories to get the latest versions of software (notably Nginx, Apache, PHP) which are not available on Debian using the same method of installation. 

PPA repositories are specific to Ubuntu (although they may make their way into Debian), so I think running the scripts as is would generate some errors and stop execution.

**Comment by jackyliang** [comment]
Hi fide!

Earlier I tried to be creative and change the OS to Debian 8.0. And after running vagrant up, Debian was indeed installed, but unsurprisingly, none of the dependencies were installed - apache2, PHP, composer, Laravel. I didn't know that your script used the PPA, so it's pretty unsurprisingly it didn't work then. It all makes sense now! Thank you.

Your script has made things so much easier deploying new dev environments - thank you.

Is there a reason to not use this over Ansible?

Regards,

Jacky Liang

**Comment by fideloper** [comment]
Definitely use ansible if you know it! This started as a way to learn more
(and teach people the basics). I'm working on https://github.com/vagrant-ops
as a vagrant-based solution (which is more likely to also support
debian/centos, etc).

Check it out!

**Comment by jackyliang** [comment]
Hi @fideloper, thanks for your prompt replies. 

I have some more questions. Laravel suggests we use Homestead (which is still vagrant). My question is - what's the difference between what you have and Homestead? Homestead by default doesn't install all the fancy vim, MySQL, Apache2, etc, which is what I love about yours. Would running your `.sh` scripts install things for me within Homestead?

**Comment by fideloper** [comment]
Running the .sh scripts here for the most part should be OK on Homestead, but Homestead installs a pretty good configuration.

One thing to know is that Homestead will have Nginx on it already, so you'll need to turn that off before installing Apache (they'll conflict when trying to listen on port 80/443 for http connections). 

Some scripts here may make assumptions about what's installed from other scripts (base.sh and php.sh are assumed to always have run, for example). For the most part that probably won't be an issue.
