### ISSUE TITLE
Error 404 - File Not Found

### ISSUE THREAD

**Issue by heyalbert** [fideloper/Vaprobash#468]
I installed a fresh vagrant machine with Symfony and NGINX, but after I got:

    // Opened: http://project.app/app_dev.php 

https://cl.ly/image/3D2M1N1h1W0f

    404 NOT FOUND

and

// Opened http://project.app/app.php or http://project.app

https://cl.ly/image/3G0Q47240G0p

My nginx config:

    server {
            listen 80;
    
            root /vagrant/symfony/web;
            index index.html index.htm index.php app.php app_dev.php;
    
            # Make site accessible from ...
            server_name 192.168.22.10.xip.io handshake.dev;
    
            access_log /var/log/nginx/vagrant.com-access.log;
            error_log  /var/log/nginx/vagrant.com-error.log error;
    
            charset utf-8;
    
            location / {
                try_files $uri $uri/ /app.php?$query_string /index.php?$query_string;
            }
    
            location = /favicon.ico { log_not_found off; access_log off; }
            location = /robots.txt  { access_log off; log_not_found off; }
    
            error_page 404 /index.php;
    
            # pass the PHP scripts to php5-fpm
            # Note: .php$ is susceptible to file upload attacks
            # Consider using: "location ~ ^/(index|app|app_dev|config).php(/|$) {"
            location ~ .php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+.php)(/.+)$;
                # With php5-fpm:
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param LARA_ENV local; # Environment variable for Laravel
                fastcgi_param HTTPS off;
            }
    
            # Deny .htaccess file access
            location ~ /\.ht {
                deny all;
            }
        }
    
        server {
            listen 443;
    
            ssl on;
            ssl_certificate     /etc/ssl/xip.io/xip.io.crt;
            ssl_certificate_key /etc/ssl/xip.io/xip.io.key;
    
            root /vagrant/symfony/web;
            index index.html index.htm index.php app.php app_dev.php;
    
            # Make site accessible from ...
            server_name 192.168.22.10.xip.io handshake.dev;
    
            access_log /var/log/nginx/vagrant.com-access.log;
            error_log  /var/log/nginx/vagrant.com-error.log error;
    
            charset utf-8;
    
            location / {
                try_files $uri $uri/ /app.php?$query_string /index.php?$query_string;
            }
    
            location = /favicon.ico { log_not_found off; access_log off; }
            location = /robots.txt  { access_log off; log_not_found off; }
    
            error_page 404 /index.php;
    
            # pass the PHP scripts to php5-fpm
            # Note: .php$ is susceptible to file upload attacks
            # Consider using: "location ~ ^/(index|app|app_dev|config).php(/|$) {"
            location ~ .php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+.php)(/.+)$;
                # With php5-fpm:
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
              include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param LARA_ENV local; # Environment variable for Laravel
                fastcgi_param HTTPS on;
            }
    
            # Deny .htaccess file access
            location ~ /\.ht {
                deny all;
            }
        }

What is wrong?

**Comment by fideloper** [comment]
Sorry I never answered this. Best guess there is that the `root` is incorrect (`root /vagrant/symfony/web;`) or `try_files` could neither find neither index.php nor app.php.

Although I would first have tried to see if Nginx had an issue with the resulting configuration via the `sudo service configtest nginx` command. Perhaps it didn't reload Nginx sine it didn't like part of the config.
