### ISSUE TITLE
Vagrant share ssl produced 400 bad request on apache

### ISSUE THREAD

**Issue by wasimkham** [fideloper/Vaprobash#469]
I'm using vaprobash with apache2 and trying to using vagrant share.

vagrant share --https 443

It all starts fine and provides a URL. When I access that URL I'm presented with a 400 error:

> Bad Request
> 
> Your browser sent a request that this server could not understand. Apache/2.4.12 (Ubuntu) Server at*.vagrantshare.com Port 443```

I have been accessing the vagrant machine using https just fine, but it doesn't seem to like to work with vagrant share.

I've used vagrant share before on a fresh vagrant install and didn't see this issue.

**Comment by fideloper** [comment]
SSL's assume you're accessing the site from a specific domain. The SSL used on Vaprobash out of the box is `*.xip.io` (where the * is the IP of vaprobash).

Vagrant share is likely accessing VM via a different hostname (`Host` header is probably sent to the VM as whatever host your vagrant share URL is).

I'm not sure if vagrantshare has a work-around for that or not. I don't see any mention of it in the docs. I think you'd have to create a (self-signed) ssl certificate for the hostname given to you by vagrant share. You can see how Vaprobash's is created here:  https://github.com/fideloper/Vaprobash/blob/master/scripts/base.sh#L37-L57
