### ISSUE TITLE
Because the NodeJS website has changed setting $NODEJS_VERSION to "latest" now returns null

### ISSUE THREAD

**Issue by connerbw** [fideloper/Vaprobash#471]
When I set $NODEJS_VERSION to latest, installer fails.

Checked the website, it's back to $3 today....

Ie. revert: https://github.com/fideloper/Vaprobash/commit/0c6e00096d03b020a86bb84198515281de26e950

Suggested patch:
```
NODEJS_VERSION=`curl -Ls 'nodejs.org' | grep 'Current Version' | awk '{ print $3 }' | awk -F\< '{ print $1 }'`
```

**Comment by lukewaite** [comment]
Seems that this has been reverted, so have closed my PR and recommend closing this issue.

**Comment by connerbw** [comment]
@lukewaite  is correct. The setting it has reverted. Issue can be closed.
