### ISSUE TITLE
Error installing Composer, line 59: syntax error near unexpected token `else'

### ISSUE THREAD

**Issue by connerbw** [fideloper/Vaprobash#474]
On Xubuntu 14.04, in standard Bash:

```
==> Vaprobash: >>> Installing Composer
==> Vaprobash: #!/usr/bin/env php
==> Vaprobash: All settings correct for using Composer
==> Vaprobash: Downloading...
==> Vaprobash: 
==> Vaprobash: Composer successfully installed to: /home/vagrant/composer.phar
==> Vaprobash: Use it: php composer.phar
==> Vaprobash: /tmp/vagrant-shell: line 59: syntax error near unexpected token `else'
==> Vaprobash: /tmp/vagrant-shell: line 59: `    else'
```

Apparently, this line?

https://github.com/fideloper/Vaprobash/blob/master/scripts/composer.sh#L59

Introduced here:

https://github.com/fideloper/Vaprobash/commit/a486a23c01e772f66cd35dd2e44dcb7ab7fced51

**Comment by connerbw** [comment]
Nobug.

Need to update my Vagrantfile to include:

```
# Because this:https://developer.github.com/changes/2014-12-08-removing-authorizations-token/
# https://github.com/settings/tokens
github_pat          = "c969c72e985ac1f6b72430388b32b0e3c8abfc3b"
```

Sorry.

**Comment by fideloper** [comment]
Gotcha! No worries! :D

**Comment by fideloper** [comment]
Also, if that's your real github token, you may want to re-generate it
since it's on this issue now!

**Comment by connerbw** [comment]
No, it's not my token, I cut & paste it from https://github.com/fideloper/Vaprobash/commit/a486a23c01e772f66cd35dd2e44dcb7ab7fced51
