### ISSUE TITLE
Vagrant up doesn't work only uncommented apache

### ISSUE THREAD

**Issue by xus** [fideloper/Vaprobash#488]
Hi there,

Today I needed to run a new machine only with apache but it doesn't works for me.

I just did this:

    curl -L http://bit.ly/vaprobash > Vagrantfile

Edited my vagrantfile just uncommented this line. (Apache web server)
    
    config.vm.provision "shell", path: "#{github_url}/scripts/apache.sh", args: [server_ip, public_folder, hostname, github_url]

But vagrant up doesn't work :S . The same like this issue. https://github.com/fideloper/Vaprobash/issues/439

All help are welcome.

**Comment by burntspaghetti** [comment]
I will be using Nginx until this issue with Apache is fixed.

**Comment by fideloper** [comment]
Should be resolved via #489
