### ISSUE TITLE
There was a problem with the editor 'vi'

### ISSUE THREAD

**Issue by bjorntheart** [fideloper/Vaprobash#494]
I really like the way you setup vim in Vaprobash so I am using it outside of Vaprobash and installed it on my Mac Pro running Yosemite.  I ran into an issue when I do a `git commit`. When I save and exit vim I see the following error in terminal
```bash
error: There was a problem with the editor 'vi'.
Please supply the message using either -m or -F option.
```
I got an exit code of  `1` when inspecting it with `echo $?`

I made a backup of the .vimrc and deleted the original vimrc. I ran `git commit` again, and all is fine. Seems like something int the .vimrc file.

**Comment by fideloper** [comment]
I think that was all taken originally from my Mac setup as well, should work in theory. Did you definitely replace instances of the `vagrant` username with your Mac's username from that bash script? The script installs Vundle to handle Vim packages - but there are assumptions about what user it installs into.

**Comment by bjorntheart** [comment]
yep, I replaced the vagrant instances

**Comment by bjorntheart** [comment]
`git config --global core.editor $(which vim) ` fixed the issue

**Comment by f4usto** [comment]
+1 @bjorntheart 
git config --global core.editor $(which vim) fixed the issue for me

**Comment by ianwoolf** [comment]
+1:
git config --global core.editor $(which vim) fixed the issue for me

**Comment by fideloper** [comment]
Hello! Are you wll also using the vim install script as well? Or does this
happen even without it?

**Comment by mcfullard** [comment]
+1: 
git config --global core.editor $(which vim)

I had to restart my machine first though (after having upgraded to VIM 8.0)
