### ISSUE TITLE
How would we integrate gunicorn and Django ?

### ISSUE THREAD

**Issue by mrgodhani** [fideloper/Vaprobash#495]
I really like vaprobash. It would be cool if we have django & gunicorn option in the script too.

**Comment by fideloper** [comment]
hmmm, there is a fair bit of PHP assumed around there, altho I think most
of it checks if PHP is installed before doing PHP-specific stuff.

Python would be missing some dependencies most likely in general. Gunicorn
would need some extra config setup, I'll bet using Phusion Passenger would
be easier thanks to its "easy" nginx integration.

**Comment by mrgodhani** [comment]
Guess Phusion works for now. Thanks.
