### ISSUE TITLE
Is there a possiblity to install arbitrary packages?

### ISSUE THREAD

**Issue by andrewtch** [fideloper/Vaprobash#498]
Like passing an array of packages to base.sh, and install them automatically. This should be a very minor update, I suppose, I can PR if needed.

**Comment by fideloper** [comment]
You can use the last line of the script to include a local bash script,
which is the least complicated way.

From passed experience leaving something too open ends up getting complex
and goers you lots of support/issues opened !

**Comment by andrewtch** [comment]
Indeed. However, there is a question on how to force Vagrant to load provision scripts with self-signed SSL. Are aware of any?

**Comment by andrewtch** [comment]
Ah, nevermind. Curl and inline script to | /bin/bash is just fine, closing.
