### ISSUE TITLE
php auto_prepend_file when using Apache

### ISSUE THREAD

**Issue by rbruhn** [fideloper/Vaprobash#500]
Running Vaprobash using Apache and PHP5-FPM you cannot use php_value in .htaccess files. I've read about .user.ini files but doesn't work with fpm I guess. I cannot use the php.ini file due to running various sites on the same local server. Anyone know how I might accomplish auto_prepend_file for only one site?

**Comment by andrewtch** [comment]
Just ssh, install libapache2-mod-php5 and configure it manually (no fpm).

**Comment by rbruhn** [comment]
Thanks. Was looking for how it was done just using FPM but from what I've read online it seems pretty difficult.
