### ISSUE TITLE
Vaprobash with private fork / clone

### ISSUE THREAD

**Issue by tommedema** [fideloper/Vaprobash#501]
Hi,

We're trying to use Vaprobash inside our company. Because we have some sensitive configuration settings and architectural files within our vaprobash fork, we'd like to make our github branch private.

However, even after setting a `github_pat` in the Vagrantfile, curl fails to download files from our private repo, returning a 404 error -- I expect this is because of authentication issues. We tried to clone the entire repo locally and set the github url to `.` (this folder), but then the problem is that helpers like `vhost.sh` cannot be downloaded from within the virtual machine (e.g. in `apache.sh`).

Have you ever tried this yourself? Is there a good way to do this?

**Comment by fideloper** [comment]
Gotcha, interesting! I think you'll end up needing to clone a copy of your
repository to a local folder, and use local file paths instead of URLs, or
perhaps clone the repository to a local network and use those URLs instead
of the github ones.

**Comment by tommedema** [comment]
Okay, that'd be the easy way, but then we can't track the changes you make here, right?

**Comment by lukewaite** [comment]
@tommedema Perhaps explaining our use case will help you figure out the best way for you to do it.

We maintain a private fork of Vaprobash. It has been customized and tuned to our needs. We track Vaprobash by setting it as an additional remote on our working copy. 

Changes to Vaprobash (upstream) can be merged in, then pushed up to origin, where other members of our team pull down the latest version when required.

```
 ~/its-a-box   master 
 git remote -v
luke-upstream	git@github.com:lukewaite/Vaprobash.git (fetch)
luke-upstream	git@github.com:lukewaite/Vaprobash.git (push)
origin	git@<redacted>/its-a-box.git (fetch)
origin	git@<redacted>/its-a-box.git (push)
upstream	git@github.com:fideloper/Vaprobash.git (fetch)
upstream	git@github.com:fideloper/Vaprobash.git (push)
```

**Comment by chrispelzer** [comment]
@lukewaite 
Until https://github.com/fideloper/Vaprobash/pull/493, the github_pat wasn't being set to ```/scripts/composer.sh```, which you probably are installing to clone from the private repos.

**Comment by chrispelzer** [comment]
@lukewaite Thinking a bit more about this. How are you needing the Github Personal Access Token exposed? Expanding on my previous comment, the github_pat is only being exposed to composer, if you aren't using composer but still want the github_pat passed to something else, it will need to be added.
