### ISSUE TITLE
Editing Beanstalkd

### ISSUE THREAD

**Issue by rbruhn** [fideloper/Vaprobash#503]
The last couple times I've started a new box from scratch, I've seen /etc/default/beanstalkd does not include the #START=yes so it's never put in the file. Not sure if this is something new or not. I've had to go in and add this myself after the box is built. Is beanstalk no longer putting this in there?

Anyway, I use a local script to check and see if it's there, as well as removing the comment for BEANSTALKD_EXTRA. Thought I would post it in case you want to check it out.

```
#!/usr/bin/env bash

# Set for persistent job storage.
sudo sed -i "s/#BEANSTALKD_EXTRA/BEANSTALKD_EXTRA/" /etc/default/beanstalkd

# Check if START exists, change or add as necessary
if grep -q "#START=yes" /etc/default/beanstalkd >/dev/null 2>&1; then
    sudo sed -i "s/#START=yes/START=yes/" /etc/default/beanstalkd
else
    echo -n "START=yes" >> /etc/default/beanstalkd
fi

sudo service beanstalkd restart
```

**Comment by fideloper** [comment]
My guess is Beanstalkd will start on system boot regardless of that setup,
or another mechanism is in place to decide if it should start on boot -
something to investigate for sure!
