### ISSUE TITLE
Node.js installation through nodejs.sh fails, script returns emtpy string instead of latest version

### ISSUE THREAD

**Issue by addorange** [fideloper/Vaprobash#506]
Hi fideloper,

unfortunately it seems like the node.js install script fails to get the latest version. Instead it returns an empty string. I just tried the relevant shell commands in the terminal and it fails. Is there anything I'm missing?

    vagrant@boerse2013:/vagrant/www$ NODEJS_VERSION=`curl -L 'nodejs.org' | grep 'Current Version' | awk '{ print $4 }' | awk -F\< '{ print $1 }'`
    vagrant@boerse2013:/vagrant/www$ echo $NODEJS_VERSION
    [nothing printed]
    vagrant@boerse2013:/vagrant/www$

Within the provisioning it fails the same way as it tries to alias an empty string to 'default'.

I'm not quite experienced within the command line stuff, but maybe there is a bug and a fix to it.

Kind regards and thank you very much for Vaprobash,

Chris

**Comment by fideloper** [comment]
Believe this has been fixed !
