### ISSUE TITLE
Update to Ubuntu 16.04

### ISSUE THREAD

**Issue by aasanchez** [fideloper/Vaprobash#571]
Vaprobash need a full update to ubuntu 16.04, this mean update for a lot of scripts, a lot of PPA... a full renew of this project

**Comment by dillonraphael** [comment]
Agreed. I'm currently having issues with node and have a feeling it has to do with this issue.

**Comment by tscheckenbach** [comment]
I don't know if this comment is OK but you can try my fork: https://github.com/tscheckenbach/Vaprobash/tree/feature/xenial

Not all packages are updated yet, but the main stuff should work well.

@fideloper just say if I should delete this comment.

**Comment by fideloper** [comment]
Nope, def have at it, I'm too pressed for time lately!

Thanks

**Comment by tscheckenbach** [comment]
I added a new version for 18.04 Bionic Beaver 
https://github.com/tscheckenbach/Vaprobash/tree/feature/bionic-beaver
