### ISSUE TITLE
"vboxsf" file system is not available

### ISSUE THREAD

**Issue by LimeBlast** [fideloper/Vaprobash#92]
I've just tried using Vaprobash for the first time, but run into a bit of a problem. Here is my Vagrantfile (as you can see, nothing special):

https://gist.github.com/LimeBlast/266ea216c06fe5553094

Upon running `vagrant up`, I get the following output:

https://gist.github.com/LimeBlast/bfe8540e22857fe8c96c

I've done some research, and a lot of people have suggested that updating the Guest Additions package will help - but I'm not totally sure how I'd go about doing this (and none of the other vagrant scripts I've use have this problem (such as https://puphpet.com/ and https://github.com/bryannielsen/Laravel4-Vagrant)

I'm running Windows 7 host, with VirtualBox 4.3.6 and Vagrant 1.4.3.

Thank you.

**Comment by totoo-guo** [comment]
@LimeBlast you are right. Thanks!

**Comment by mhuckaby** [comment]
I had success by following the advice from meshr-net (modified for my VBox version):

sudo ln -s /opt/VBoxGuestAdditions-4.3.14/lib/VBoxGuestAdditions /usr/lib/VBoxGuestAdditions


And then the advice from tongkang:

vagrant ssh
sudo /etc/init.d/vboxadd setup
vagrant halt
vagrant up

Thanks.

**Comment by antonioribeiro** [comment]
Bumped into this one too...

Had to edit the `src\homestead.rb` and change

    mount_opts = folder["type"] == "nfs" ? ['actimeo=1'] : []

to 

    mount_opts = folder["type"] == "nfs" ? [''] : []

Then

	C:\Homestead> vagrant plugin install vagrant-vbguest
	C:\Homestead> vagrant up
	C:\Homestead> vagrant ssh
	$ sudo ln -s /opt/VBoxGuestAdditions-4.3.18/lib/VBoxGuestAdditions /usr/lib/VBoxGuestAdditions
	$ sudo apt-get install --yes dkms linux-headers-3.16.0-23-generic
	$ sudo /etc/init.d/vboxadd setup
	$ exit
	C:\Homestead> vagrant halt 
	C:\Homestead> vagrant up
